name: flake8_lint
on:
  # set the workflow trigger to push and pull request events
  # only for dev branch
  push:
    branches: dev
  pull_request:
    branches: dev
jobs:
  flake8_lint:
      env:
        PYTHONDONTWRITEBYTECODE: 1
        PYTHONPYCACHEPREFIX: "/dev/null"
      strategy:
        # by default, github cancels all in-progress jobs if matrix jobs fail
        fail-fast: false
        matrix:
          os: [ubuntu-latest]
          python-version: [3.8, 3.7, 3.6]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
          with:
            repository: ${{ github.repository }}
            persist-credentials: false
        - uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
            architecture: "x64"
        - name: Install linting modules
          run:
            pip3 install --no-cache-dir flake8 codespell
        - name: Python style check - black
          if: matrix.python-version >= 3.6
          run: |
            pip3 install --no-cache-dir black
            black --check . || true
        - name: Python linting check - flake8
          run:
            # flake error codes reference (https://flake8.pycqa.org/en/latest/user/error-codes.html)
            # pycodestyle error codes reference (https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes)
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        - name: Python spell check - codespell
          run:
            codespell --quiet-level=2 || true
